/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "hzietdzwgqrcfygqmxme"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6aWV0ZHp3Z3FyY2Z5Z3FteG1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MTM3OTYsImV4cCI6MjA3NDM4OTc5Nn0.5n8CLB9gE4C9S2CY0kmuixsKVmSn9IHy3-_P5axf21E"
